app = "whatsapp-bot-economia"

primary_region = "iad"  # iad = Virgínia, gratuita

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[experimental]
  auto_rollback = true

[deploy]
  strategy = "immediate"
